sudo: false
addons:
  apt:
    packages:
      - aspell
language: perl
perl:
# for what versions are available, see:
# https://github.com/travis-ci/travis-cookbooks/blob/master/ci_environment/perlbrew/attributes/multi.rb
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
before_install:
  - export AUTOMATED_TESTING=1
  - git config --global user.name "TravisCI"
  - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
install:
  - cpanm --quiet JSON::PP
  - "dzil authordeps | cpanm --quiet --notest"
  - "dzil listdeps   | cpanm --verbose"
script:
  - dzil smoke --release --author
